# -*- coding: utf-8 -*-
"""Bologna_def.ipynb

Automatically generated by Colab.

Original file is located at

"""

import os
from google.colab import files

# Crea la cartella se non esiste
if not os.path.exists('data'):
    os.makedirs('data')
    print("Cartella 'data' creata.")


print("Seleziona i file .geojson dal tuo computer:")
uploaded = files.upload()


for filename in uploaded.keys():
    os.rename(filename, os.path.join('data', filename))

print("File pronti nella cartella 'data':", os.listdir('data'))

pip install city2graph

import geopandas as gpd
import city2graph as c2g
import pandas as pd
import networkx as nx
from shapely.geometry import LineString, MultiLineString, Polygon, MultiPolygon, Point
import rasterio
from shapely.ops import unary_union, linemerge, snap
import pickle
import glob




# 1. LOAD AND ALIGN DATA

path_pedonali = "data/carta-tecnica-comunale-percorsi-pedonali (1).geojson"
path_ciclabili = "data/piste-ciclopedonali.geojson"
path_stradali = "data/aree-stradali.geojson"
path_portici = "data/portici.geojson"
path_aree_verdi = "data/carta-tecnica-comunale-toponimi-parchi-e-giardini (1).geojson"

gdp_pedonali  = gpd.read_file(path_pedonali).to_crs(3857)
gdp_ciclabili = gpd.read_file(path_ciclabili).to_crs(3857)
gdp_stradali = gpd.read_file(path_stradali).to_crs(3857)
gdp_portici   = gpd.read_file(path_portici).to_crs(3857)
gdp_aree_verdi = gpd.read_file(path_aree_verdi).to_crs(3857)


# 2. EXTRACT LINES FROM ALL GEOMETRIES

print('inizio fase 2')
def extract_lines(gdf):
    lines = []
    for geom in gdf.geometry:
        if isinstance(geom, LineString):
            lines.append(geom)
        elif isinstance(geom, MultiLineString):
            lines.extend(list(geom.geoms))
        elif isinstance(geom, Polygon):
            lines.append(geom.exterior)
        elif isinstance(geom, MultiPolygon):
            for p in geom.geoms:
                lines.append(p.exterior)
    return lines

lines_pedonali  = extract_lines(gdp_pedonali)
lines_ciclabili = extract_lines(gdp_ciclabili)
lines_stradali = extract_lines(gdp_stradali)
lines_portici   = extract_lines(gdp_portici)

print('inizio fase allineamento')
#allineo le linee che si sovrappongono
geom_stradale = unary_union(lines_stradali)
geom_pedonale = snap (unary_union(lines_pedonali), geom_stradale, 1.0)
geom_ciclabile = snap(unary_union(lines_ciclabili), geom_pedonale, 1.0)

#rete unica
geom_base = unary_union([geom_stradale, geom_pedonale, geom_ciclabile])
lines_base = linemerge(geom_base)

gdf_rete = gpd.GeoDataFrame(geometry=list(lines_base.geoms)
                            if lines_base.geom_type == "MultiLineString"
                            else [lines_base],
                            crs = "EPSG:3857"
)
print('fine fase di allineamento')
#riaggiungo i flag che si erano persi quando è stata unita la rete
# gdf_rete: rete unificata
# gdp_ciclabili: linee ciclabili originali
gdf_ped_orig = gpd.GeoDataFrame(geometry=[geom_pedonale], crs="EPSG:3857")
gdf_cic_orig = gpd.GeoDataFrame(geometry=[geom_ciclabile], crs="EPSG:3857")
gdf_str_orig = gpd.GeoDataFrame(geometry=[geom_stradale], crs="EPSG:3857")



def get_predominant_mask(network_gdf, original_lines_gdf, threshold=0.5):
    """
    Ritorna una maschera booleana per i segmenti che si sovrappongono
    significativamente alle linee originali.
    """
    # 1. Creiamo un piccolo buffer attorno alle linee originali (es. 0.5 metri)
    # per compensare piccoli errori di precisione numerica dello snap
    original_buffer = original_lines_gdf.buffer(0.5)
    union_buffer = original_buffer.union_all()

    # 2. Calcoliamo l'intersezione spaziale tra la rete e il buffer
    # intersection() calcola la parte di geometria comune
    intersections = network_gdf.geometry.intersection(union_buffer)

    # 3. Calcoliamo la percentuale di copertura
    # Se la lunghezza dell'intersezione / lunghezza totale > soglia -> True
    coverage_ratio = intersections.length / network_gdf.geometry.length

    return coverage_ratio > threshold

print('aggiunta dei flag')
gdf_rete["is_pedonale"] = get_predominant_mask(gdf_rete, gdf_ped_orig)
gdf_rete["is_ciclabile"] = get_predominant_mask(gdf_rete, gdf_cic_orig)
gdf_rete["is_stradale"] = get_predominant_mask(gdf_rete, gdf_str_orig)



def get_modes(row):
    modes = []
    if row["is_pedonale"]: modes.append("pedonale")
    if row["is_ciclabile"]: modes.append("ciclabile")
    if row["is_stradale"]:  modes.append("stradale")
    return modes if modes else ["unknown"]

gdf_rete["mode"] = gdf_rete.apply(get_modes, axis=1)

# Aggiungi un flag ciclabile usando sjoin
# ciclabile

gdf_portici = gpd.GeoDataFrame(
    {"portico":[1]*len(lines_portici)},
    geometry = lines_portici,
    crs = "EPSG:3857"
)

buffer_portici = gdf_portici.buffer(6)
buffer_union = buffer_portici.union_all()


# 3. CREATE BASE GRAPH FROM CITY2GRAPH (OSMWayNode + Way)

print('inizio fase 3')
nodes_gdf, edges_gdf = c2g.segments_to_graph(gdf_rete)

# mark edges under portico

edges_gdf["portico"] = edges_gdf.geometry.apply(lambda g: int(g.intersects(buffer_union)))
G = c2g.gdf_to_nx(nodes_gdf, edges_gdf)
print("Base graph created:", G)

import os
#from google.colab import files

# Crea la cartella se non esiste
if not os.path.exists('data'):
    os.makedirs('data')
    print("Cartella 'data' creata.")

print("Seleziona i file .geojson dal tuo computer:")
uploaded = files.upload()


for filename in uploaded.keys():
    os.rename(filename, os.path.join('data', filename))

print("File pronti nella cartella 'data':", os.listdir('data'))

from pyproj import Transformer


first_node = list(G.nodes(data=True))[4]
print(f"Esempio nodo: {first_node}")

import os
import glob
import rasterio
from rasterio.transform import Affine
from rasterio.crs import CRS
import networkx as nx


# 1. Legge transform dal file .tfw


def read_tfw(tfw_path):
    with open(tfw_path, "r") as f:
        A = float(f.readline())  # pixel size X
        D = float(f.readline())  # rotation
        B = float(f.readline())  # rotation
        E = float(f.readline())  # pixel size Y (negative)
        C = float(f.readline())  # top left X
        F = float(f.readline())  # top left Y

    return Affine(A, B, C, D, E, F)


# 2. Legge CRS dal file .prj


def read_prj(prj_path):
    with open(prj_path, "r") as f:
        wkt = f.read()
    return CRS.from_wkt(wkt)


# 3. Carica tutti i raster con georeferencing


def load_rasters(folder):

    raster_files = glob.glob(os.path.join(folder, "*.tif"))

    rasters = []

    for tif_path in raster_files:

        base = os.path.splitext(tif_path)[0]

        tfw_path = base + ".tfw"
        prj_path = base + ".prj"

        if not os.path.exists(tfw_path):
            print(f"TFW mancante per {tif_path}")
            continue

        if not os.path.exists(prj_path):
            print(f"PRJ mancante per {tif_path}")
            continue

        transform = read_tfw(tfw_path)
        crs = read_prj(prj_path)

        ds = rasterio.open(tif_path)

        bounds = rasterio.transform.array_bounds(
            ds.height,
            ds.width,
            transform
        )

        rasters.append({
            "dataset": ds,
            "transform": transform,
            "bounds": bounds,
            "crs": crs
        })

    print(f"Caricati {len(rasters)} raster correttamente")

    return rasters


# 4. Estrae elevazione da coordinate lon/lat


def get_elevation(lon, lat, rasters):

    for r in rasters:

        left, bottom, right, top = r["bounds"]

        if left <= lon <= right and bottom <= lat <= top:

            transform = r["transform"]

            col, row = ~transform * (lon, lat)

            col = int(col)
            row = int(row)

            ds = r["dataset"]

            if 0 <= row < ds.height and 0 <= col < ds.width:

                elevation = ds.read(1)[row, col]

                if elevation < -1000:
                    return 0

                return float(elevation)

    return 0



# 5. Aggiorna grafo NetworkX


def add_elevation_to_graph(G, raster_folder):
    rasters = load_rasters(raster_folder)

    graph_crs = "EPSG:3857"


    transformers = {}
    for i, r in enumerate(rasters):
        target_crs = r["crs"]
        transformers[i] = Transformer.from_crs(graph_crs, target_crs, always_xy=True)

    count = 0
    for node_id, data in G.nodes(data=True):
        geom = data.get("geometry")

        if geom is None:
          continue

        x = geom.x
        y = geom.y

        if x is None or y is None:
            continue

        elev = 0
        for i, r in enumerate(rasters):

            lon_r, lat_r = transformers[i].transform(x, y)

            left, bottom, right, top = r["bounds"]
            if left <= lon_r <= right and bottom <= lat_r <= top:
                transform = r["transform"]
                col, row = ~transform * (lon_r, lat_r)
                col, row = int(col), int(row)

                ds = r["dataset"]
                if 0 <= row < ds.height and 0 <= col < ds.width:
             
                    window = rasterio.windows.Window(col, row, 1, 1)
                    val = ds.read(1, window=window)
                    elev = float(val[0, 0])

                    if elev < -1000: 
                        elev = 0
                    break
        G.nodes[node_id]["elev"] = elev
        count += 1

    print(f"Aggiornati {count} nodi con elevazione")
    return G
add_elevation_to_graph(G, "data")


# 4. CONVERT CITY2GRAPH NODES TO OSMWayNode STRUCTURE


for node_id, data in G.nodes(data=True):
    geom = data["geometry"]

    G.nodes[node_id]["type"] = "OSMWayNode"
    G.nodes[node_id]["lat"] = geom.y
    G.nodes[node_id]["lon"] = geom.x


# 5. CREATE WAY NODES (each edge becomes a Way)


way_count = 0
for u, v, data in list(G.edges(data=True)):

    way_id = f"way_{way_count}"
    way_count += 1

  
    geom = data.get("geometry")
    length = geom.length if geom and geom.length > 0 else 1.0

    # 2. Recupera l'elevazione dei nodi estremità
    elev_u = G.nodes[u].get("elev", 0)
    elev_v = G.nodes[v].get("elev", 0)

    # 3. Gestione pendenza e dislivello
    if elev_u == 0 or elev_v == 0:
        slope_pct = 0
        delta_h = 0
    else:
        delta_h = abs(elev_v - elev_u)
        slope_pct = (delta_h / length) * 100

    # nodo Way
    G.add_node(
        way_id,
        type="Way",
        mode=data.get("mode", "unknown"),
        portico=data.get("portico", 0),
        geometry=geom,
        avg_elev=(elev_u + elev_v) / 2, # Altitudine media
        delta_h=delta_h,                # Dislivello totale
        slope_pct=slope_pct,             # Pendenza percentuale
        length = length         # Lunghezza in metri della strada
    )

    # Collega i nodi fisici al nodo Way
    G.add_edge(u, way_id, type="MEMBER_OF")
    G.add_edge(v, way_id, type="MEMBER_OF")

# 6. ADD TAG NODES (optional metadata)

tags_dict = {}

def add_tag(way_id, key, value):
    tag_id = f"tag_{key}_{value}"
    if tag_id not in tags_dict:
      G.add_node(tag_id, type="Tag", key=key, value=value)
      tags_dict[tag_id] = tag_id
    G.add_edge(way_id, tag_id, type="TAGS")


for n, d in list(G.nodes(data=True)):
    if d["type"] == "Way":
        for mode in d.get("mode"):
          add_tag(n, "highway", mode)
        if d["portico"] == 1:
            add_tag(n, "cover", "portico")

# 7. ADD POI: PARKS AS PointOfInterest
print(len(gdp_aree_verdi))
print(gdp_aree_verdi.geometry.geom_type.value_counts())

# i parchi sono già punti
park_points = gdp_aree_verdi.geometry
print(len(park_points))


nodes_geom = [(n,d) for n,d in G.nodes(data=True) if d.get("type")=="OSMWayNode" and "geometry" in d]

nodes, data = zip(*nodes_geom)

gdf_nodes = gpd.GeoDataFrame(
    {"node": nodes},
    geometry=[d["geometry"] for d in data],
    crs="EPSG:3857"
)

sindex = gdf_nodes.sindex

for i, pt in enumerate(park_points):

    print('*')

    poi_id = f"park_{i}"

    G.add_node(
        poi_id,
        type="PointOfInterest",
        subtype="park",
        x=pt.x,
        y=pt.y
    )

  
    nearest_idx = gdf_nodes.geometry.distance(pt).idxmin()
    nearest_node = gdf_nodes.loc[nearest_idx, "node"]

    G.add_edge(poi_id, nearest_node, type="NEAR")

print("Graph construction completed!")

with open("graph.pkl", "wb") as f:
    pickle.dump(G, f)

print("Grafo salvato su graph.pkl")